### ISSUE TITLE
Compilation failed after  I added a file a.ts

### ISSUE THREAD

**Issue by vikerman** [adeora/playground#30]
https://edit.ng/#,nVRRT9swEP4rt7y0nZpEoD2loerYmEAamwRMPBAe3NhtDI4d2W6hi_Lfd46brNCySTzF8X3fd.fvfK6DOFdlpSSTNrImSAKOf9pCfarVk2H6UtGVYA0stCphMCNyuRJEx5UgdqF0Gc49bDDJZMf80gmO4cfS88fwuaoEz4nlSl6xxZ5erjRzGplkz61KLogxcM60gho4TUCuyjnTE5CkZAkYq7lcQuMYuZLGwvnZ1c.z66Sl3N3DCdxlEmrHPDoab1mDU2JLIgfNuI8d97FbJSnTcKveRFxoJeFyG713qWf9WYc1EsAwwXKrNIILJoQKn5QWNCRVNXCCYFnpnGO_tEggC6K42zD9KipsKbIA4c1ozw2UvHWKfVpo0xZ4ZmbwzN6Eyd9SGHV.eFfabSWv28Cw6PdHCawVp.izLbiJdoko6XATZ3Tr9azrqD.vb7lJ4O7FdblvD0sZlq3bljvEgeo9Dhd60._9EzpXymLrSfUG6IBpl4RLX5XzqnEqAME4eMt6HIF0JTz5JAu8tVkwdcRUcPgol9.UxohgtjUH1AI6FAxzvOWPIwy_MHqEAnXtVpG7S02TxoKjZBqvhPtQvnbCFwsk7vrf5cX4NBVkzsTU30Xkt39Q17v4Xt0RnLz_dkcu0YuXU37DjD1l9OA8oi_G4pTtzva2zV83mIjnNx7QzXj3KBwE_fcJCanH76bN5LbAiEtu3fpMrjmOYelGzh_s_SUNRyPM4YzhOPrPffvd1_teMEK3_qUfwtCvAG4KBui.egKTa15ZA09cCNyCSqs1p4wClzhNDPhCY0cAS4CNWkWOqXHXgFSdmGQItwoIpY5SIjXysTCcOgu67KlPBnZTMbwnlj3b.IGsid_Ogk7Q6PxkUFhbmSSOV7J6XEb4xrctDR_M7Dj6FB3FeE_RwtgUvIxKzPhgBtM09lLTNvF70uK87OX9jaOJ8ngVje1.8F6_TpbGvdnpXNFNV8Grd3TapfuuCMUeRtHWLMffR6bxVgvDXVf9LMTET0LQ_AE

**Comment by adeora** [comment]
I pushed an update to edit.ng that fixed one of the issues: now the error console displays `File '/a.ts' not found. (, )` on compilation.

Seems that your error is related to the use of TestBed.initTestEnvironment in `main.ts`. Starting with a fresh project and adding a blank `a.ts` file successfully compiles, as expected. See below link for repro.

https://edit.ng/#,nVVNb6MwEP0rs1xIVgHUak8JjdKuWrXStiu1XfVQenDAAbfGRrZJmkX89x3jQNOvlXZPGM.89zzPw9B4USrLSgoqTGi0N_UYvikDzYmSG03VpcxqTltYKVmCvyAirzlRUcWJWUlVBkuX5s8S0SO_94QTuModfgLHVcVZSgyT4pqu3vGlUlHLkQj63LGknGgN51RJaIBlUxB1uaRqBoKUdAraKCZyaC0ilUIbOD.9_nl6M.0g9w9wBPeJgMYiDw4mO5R_QkxJhN9OhtjhELuTIqMK7uSnGRdKCrjcRR.s9GKoddQgADTlNDVSYXJBOZfBRiqeBaSqfEsIhpbWOfpL8SkkXhj1G3pYhYUpeeJhejt.5wZS3lnGQRY62QJrphprdibMXo5CM.uHc6XbluKmC4yKYX88hbVkGfpsCqbDfSBS2ryZNbrzetHfqKvXXbmewv2rdnnois0oHlt1V24zPji9y8OF2g57f01dSmnw6kn1SdIHpl0SJtyprFetZQHwJt5n1uMnENfcgY8Sz1mbeHMLjDmDryI_kwojnJrOHJAr6LNglGKXP40x_MroMRI0jV2FtpfaNo44Q8o4qrl9ZGxtiS9WCNz3v9fF.DzmZEn53PUi4rs3aJr9_IHdAiy9e_YlM.zw56FK.3T0BSXZLi3.EgRuBXBbUEARuQGdKlYZDRvGOW5BpeSaZTQDJrBpKLCVQmHAiQBbWYcWqXBXg5A9maCYbiSQLLOQEqGhiwXB3LZWrx47MTDbiqIdhj6b6JGsidtOvJ5Qq_TIL4yp9DSKalE95SGOsm6SBI96cRh.Cw8ivA7si0gXrAxLVHzU_jyOHNW8E_4fWWyLd7q_sQORHh3Xpn_B63srFkeD2fFSZtv.BG_GxbyX.yFJhpMuDHdmWfz7zDjacWG4v1V35SW2vxvsLwMa.um9.2jhn8b73hd1lZ8RO.62A0O49zsR.cpF3WC3Y1pyGnKZj_zrWgg7wI9_3oJFME4zf4x5b442GofDN.80d4qjD04xnr3UTVzRXvsH

**Comment by adeora** [comment]
We should check if the original issue is also present on a standard AOT app (i.e. one not built in edit.ng). If so, then edit.ng is working as expected.
